version: '3.8'
services:  
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 #{port in host(myPC)} : {port in Container}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12344321
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
 nestjs-network:

 # docker exec -it dev-database bash run a bash shell inside a Container
 # psql -U postgres -W testdb     U user W name db
 #\dt
 